# Generated by Django 5.2.9 on 2026-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0255_remove_system_settings_product_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dojo_group",
            name="social_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AzureAD", "AzureAD"),
                    ("Remote", "Remote"),
                    ("SAML2", "SAML2"),
                ],
                help_text="Group imported from a social provider.",
                max_length=10,
                null=True,
                verbose_name="Social Authentication Provider",
            ),
        ),
    ]
